version: "3.8"
services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo-data:/data/db
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883" #default mqtt port
    volumes:
      - ./mosquitto_config:/mosquitto/config:rw
