version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: stack-on:test
    environment:
      PORT: 3000
      MONGO_CONNECTION_URL: mongodb://root:root@mongodb:27017
      MQTT_BROKER_URL: tcp://mosquitto:1883
      MCP_PORT: 3001
      MCP_ENABLED: true
    networks:
      - backend
    ports:
      - 8080:3000
      - 8081:3001

  # Prerequisites
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo-data:/data/db
    networks:
      - backend

  # Allow anonymous access to mosquitto (for testing)
  # Place these lines in the mosquitto.conf file

  # allow_anonymous true
  # listener 1883
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto_config:/mosquitto/config:rw
    networks:
      - backend
networks:
  backend:
